import { JSEncrypt } from 'jsencrypt';

// Public key generated by scripts/generate_rsa_keys.py
const PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtvhcwFrSI+xLKbrO60+r
gTzr7FjF/WzG7GW4z1C57ut7Lfxdn6pdDM+ytgf12uS9PLjlNnFzZ9G6GgzV3iEg
Q3fXstw3rLr8f+bAaWdkQ/Odzojh5K+nUejYKKd+nLovKAkYDKZ1gHBtBaYjtAQp
mts1vphZp4irs4YT1bnUD461UAWL5I/u8Vs1f5i8vendhedYRM7zzwgHDM7D827g
3OSTinT34FvN7hLsQoWBMUKla/wqGw6nBR2/07cAGY17+PSom+ZX85e3Bk6cBfmN
gxUz2Jv3ke4sf4pexTNRnAWVQnzvQjptjPVIiWKb6cTqmt748JH9jvwo3f2WoMvg
GQIDAQAB
-----END PUBLIC KEY-----`;

let _encryptor = null;

function _getEncryptor() {
  if (_encryptor) return _encryptor;
  _encryptor = new JSEncrypt();
  _encryptor.setPublicKey(PUBLIC_KEY_PEM);
  return _encryptor;
}

export function warmupCrypto() {
  _getEncryptor();
}

export async function encryptLoginPayload(username, password) {
  const enc = _getEncryptor();
  const result = enc.encrypt(JSON.stringify({ username, password }));
  if (!result) throw new Error('Encryption failed — public key may be invalid');
  return result;
}
