// Public key generated by scripts/generate_rsa_keys.py
// Replace the placeholder below with the actual PUBLIC_KEY_PEM output from that script.
const PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtvhcwFrSI+xLKbrO60+r
gTzr7FjF/WzG7GW4z1C57ut7Lfxdn6pdDM+ytgf12uS9PLjlNnFzZ9G6GgzV3iEg
Q3fXstw3rLr8f+bAaWdkQ/Odzojh5K+nUejYKKd+nLovKAkYDKZ1gHBtBaYjtAQp
mts1vphZp4irs4YT1bnUD461UAWL5I/u8Vs1f5i8vendhedYRM7zzwgHDM7D827g
3OSTinT34FvN7hLsQoWBMUKla/wqGw6nBR2/07cAGY17+PSom+ZX85e3Bk6cBfmN
gxUz2Jv3ke4sf4pexTNRnAWVQnzvQjptjPVIiWKb6cTqmt748JH9jvwo3f2WoMvg
GQIDAQAB
-----END PUBLIC KEY-----`;

let _cachedKey = null;

async function _importKey() {
  const pemBody = PUBLIC_KEY_PEM
    .replace('-----BEGIN PUBLIC KEY-----', '')
    .replace('-----END PUBLIC KEY-----', '')
    .replace(/\s+/g, '');
  const der = Uint8Array.from(atob(pemBody), c => c.charCodeAt(0));
  return crypto.subtle.importKey(
    'spki',
    der.buffer,
    { name: 'RSA-OAEP', hash: 'SHA-256' },
    false,
    ['encrypt'],
  );
}

export async function warmupCrypto() {
  if (!_cachedKey) _cachedKey = await _importKey();
}

export async function encryptLoginPayload(username, password) {
  if (!_cachedKey) _cachedKey = await _importKey();
  const encoded = new TextEncoder().encode(JSON.stringify({ username, password }));
  const encrypted = await crypto.subtle.encrypt({ name: 'RSA-OAEP' }, _cachedKey, encoded);
  return btoa(String.fromCharCode(...new Uint8Array(encrypted)));
}
